# Generated by Django 5.0.7 on 2024-09-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_youtubepost_likes_youtubecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubecomment',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='youtubecomment',
            old_name='post',
            new_name='youtube_post',
        ),
    ]
