# Generated by Django 4.2.13 on 2024-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_allcourses_alter_android_app_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalbook',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
