# Generated by Django 4.2.13 on 2024-07-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contact_message_scheduledmessage_subscriber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
