# Generated by Django 5.0.7 on 2024-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
