# Generated by Django 5.0.7 on 2024-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_otp_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
