# Generated by Django 5.0.7 on 2024-08-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp_number',
        ),
    ]
