# Generated by Django 5.0.7 on 2024-08-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fcm_token',
        ),
    ]
