# Generated by Django 5.0.7 on 2024-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
