# Generated by Django 5.0.7 on 2024-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
