# Generated by Django 5.0.7 on 2024-09-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_chatfile_delete_userfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatFile',
        ),
    ]
