# Generated by Django 4.2.13 on 2024-09-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_device_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='device_token',
            new_name='fcm_token',
        ),
    ]
