# Generated by Django 4.2.13 on 2024-10-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='forwarded_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
