# Generated by Django 4.2.13 on 2024-10-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_forwarded_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='has_received_notification',
            field=models.BooleanField(default=False),
        ),
    ]
