# Generated by Django 4.2.13 on 2024-10-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
