from django.urls import path
from . import views
from .views import (
    subscribe_author,
    edit_post,
    delete_post,
    add_marketplace_item,
    marketplace_item_detail,
    share_marketplace_item,
    YouTubePostDetailView,
)

from chat.views import (
    room,
    send,
    private_chat_view,
    room,
    assign_admin,
    revoke_admin,
    kick_member,
)
from users.views import community_guidelines

urlpatterns = [
    path('youtube/delete_comment/<int:comment_id>/', views.delete_youtube_comment, name='delete_youtube_comment'),
    path('youtube/post/<str:video_id>/', YouTubePostDetailView.as_view(), name='youtube_post_detail'),
    path('youtube/like/<str:video_id>/', views.like_youtube_post, name='like_youtube_post'),
    path('youtube/comment/<str:video_id>/', views.comment_youtube_post, name='comment_youtube_post'),
    path('youtube/share/<str:video_id>/', views.share_youtube_post, name='share_youtube_post'),
    path('api/mixed-content/', views.mixed_content_api, name='mixed_content_api'),
    path('edit/<int:resource_id>/', views.edit_resource, name='edit_resource'),
    path('delete/<int:resource_id>/', views.delete_resource, name='delete_resource'),
    path('upload/', views.upload_useful_resource, name='upload_useful_resource'),
    path("community-guidelines/", community_guidelines, name="community-guidelines"),
    path("assign-admin/", assign_admin, name="assign-admin"),
    path("revoke-admin/", revoke_admin, name="revoke-admin"),
    path("kick-member/", kick_member, name="kick-member"),
    path("get-referral-link/", views.get_referral_link, name="get_referral_link"),
    path("referral/<str:referral_code>/", views.referral_link, name="referral_link"),
    path("get-coins/", views.get_coins, name="get_coins"),
    path("get_verified/", views.get_verified, name="get_verified"),
    path("buy_coins/", views.buy_coins, name="buy_coins"),
    path("wishlist/add/<int:item_id>/", views.add_to_wishlist, name="add_to_wishlist"),
    path(
        "marketplace/share/<int:item_id>/",
        share_marketplace_item,
        name="share_marketplace_item",
    ),
    path('marketplace/item/<int:item_id>/', marketplace_item_detail, name='marketplace_item_detail'),

    path("cart_view/", views.cart_view, name="cart_view"),
    path("contact/<int:item_id>/", views.contact_seller, name="contact_seller"),
    path("add-to-cart/<int:item_id>/", views.add_to_cart, name="add_to_cart"),
    path("add_marketplace_item/", add_marketplace_item, name="add_marketplace_item"),
    path("join_marketplace/", views.join_marketplace, name="join_marketplace"),
    path("search_marketplace/", views.search_marketplace, name="search_marketplace"),
    path("like/<int:post_id>/", views.like_post, name="like_post"),
    path("share/<int:post_id>/", views.share_post, name="share_post"),
    path(
        "subscribe-author/<int:author_id>/", subscribe_author, name="subscribe_author"
    ),
    path("comment/<int:post_id>/", views.add_comment, name="add_comment"),
    path(
        "delete_comment/<int:comment_id>/", views.delete_comment, name="delete_comment"
    ),
    path(
        "submit_material_request/",
        views.submit_material_request,
        name="submit_material_request",
    ),
    path("purchase_material/", views.purchase_material, name="purchase_material"),
    path(
        "search_motivational_books/",
        views.search_motivational_books,
        name="search_motivational_books",
    ),
    path("", views.home, name="home"),
    path("upload_message/", views.upload_message, name="upload_message"),
    path("upload_success/", views.upload_success, name="upload_success"),
    path("register_business/", views.register_business, name="register_business"),
    path("purchase_data/", views.purchase_data, name="purchase_data"),
    path(
        "domain_hosting_request/",
        views.domain_hosting_request,
        name="domain_hosting_request",
    ),
    path(
        "facebook_ads_requirement/",
        views.facebook_ads_requirement,
        name="facebook_ads_requirement",
    ),
    path("graphics_b/", views.graphic_b, name="graphics_b"),
    path("graphics_a/", views.graphic_a, name="graphics_a"),
    path("graphics_p/", views.graphic_p, name="graphics_p"),
    path("cyber_security_b/", views.cyber_security_b, name="cyber_security_b"),
    path("cyber_security_a/", views.cyber_security_a, name="cyber_security_a"),
    path("cyber_security_p/", views.cyber_security_p, name="cyber_security_p"),
    path("video_editing_b/", views.video_editing_b, name="video_editing_b"),
    path("video_editing_a/", views.video_editing_a, name="video_editing_a"),
    path("video_editing_p/", views.video_editing_p, name="video_editing_p"),
    path("website_requirement/", views.website_requirement, name="website_requirement"),
    path(
        "facebook_ads_requirement/",
        views.facebook_ads_requirement,
        name="facebook_ads_requirement",
    ),
    path("data_analysis/", views.data_analysis, name="data_analysis"),
    path("data_analysis_b/", views.data_analysis_b, name="data_analysis_b"),
    path("data_analysis_a/", views.data_analysis_a, name="data_analysis_a"),
    path("data_analysis_p/", views.data_analysis_p, name="data_analysis_p"),
    path("andriod_apps/", views.andriod_apps, name="andriod_apps"),
    path("desktop_apps/", views.desktop_apps, name="desktop_apps"),
    path("useful_resources/", views.useful_resources, name="useful_resources"),
    path("coding_exam_b/", views.coding_exam_b, name="coding_exam_b"),
    path(
        "digital_marketing_exam_b/",
        views.digital_marketing_exam_b,
        name="digital_marketing_exam_b",
    ),
    path("graphic_exam_b/", views.graphic_exam_b, name="graphic_exam_b"),
    path(
        "cyber_security_exam_b/", views.cyber_security_exam_b, name="cyber_security_exam_b"
    ),
    path(
        "video_editing_exam_b/", views.video_editing_exam_b, name="video_editing_exam_b"
    ),
    path(
        "data_analysis_exam_b/", views.data_analysis_exam_b, name="data_analysis_exam_b"
    ),
    path("error_message/", views.error_message, name="error_message"),
    path("upload_message/", views.upload_message, name="upload_message"),
    path("graphics/", views.graphics, name="graphics"),
    path("cyber_security/", views.cyber_security, name="cyber_security"),
    path("video_editing/", views.video_editing, name="video_editing"),
    path("coding/", views.coding, name="coding"),
    path("digital_marketing/", views.digital_marketing, name="digital_marketing"),
    path("digital_marketing_b/", views.digital_marketing_b, name="digital_marketing_b"),
    path("digital_marketing_a/", views.digital_marketing_a, name="digital_marketing_a"),
    path("digital_marketing_p/", views.digital_marketing_p, name="digital_marketing_p"),
    path("coding_b/", views.coding_b, name="coding_b"),
    path("coding_a/", views.coding_a, name="coding_a"),
    path("coding_p/", views.coding_p, name="coding_p"),
    path("about/", views.about, name="about"),
    path("terms/", views.terms, name="terms"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("post_list/", views.post_list, name="post_list"),
    path("delete_post/<int:post_id>/", delete_post, name="delete_post"),
    path("edit_post/<int:post_id>/", edit_post, name="edit_post"),
    path("send", send, name="send"),
    path("private_chat/<int:chat_id>/", private_chat_view, name="private_chat"),
    path("post/<int:post_id>/", views.post_detail, name="post_detail"),
    path("room/<int:room_id>/", room, name="room"),
    path('save-fcm-token/', views.save_fcm_token, name='save_fcm_token'),
    path("owdservices/", views.owdservices, name="owdservices"),
    path("ebooks/", views.ebooks, name="ebooks"),
]
